site_name: Kubernetes in my head
site_url: https://kubernetesinmyhead.net
theme:
  name: material
  language: es
  palette:
    scheme: default
  features:
  - navigation.path # breadcrumb navigation
  - navigation.footer # include links to the previous and next page of the current page
  - navigation.prune
  - toc.follow
  - navigation.top
extra:
  social:
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/jorge-p-275960300
    name: LinkedIn
markdown_extensions:
- toc:
    permalink: true
    title: Indice
    permalink_title: Anchor link to this section for reference
