name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write # required to push the built site to the gh-pages branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history needed by mkdocs-git-revision-date-localized to read commit dates
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # use ISO week number as cache key so it refreshes weekly
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install "mkdocs-material<2.0" mkdocs-git-revision-date-localized-plugin # mkdocs-git-revision-date-localized-plugin adds page generation date
      - run: mkdocs gh-deploy --force # build and push to gh-pages branch
